-- SQL Retail Sales Analysis Project --
create database sql_project;

-- Createing Table 
drop tables if exists retail_sales;
create table retail_sales
			(
			transactions_id	int primary key,
			sale_date date,
			sale_time time,
			customer_id	int,
            gender varchar(15),
			age int,
			category varchar(15),
			quantity int,
            price_per_unit float, 
			cogs float,
			total_sale float
            );
select * from retail_sales;
select count(*) 
	from retail_sales;

-- DATA CLEANING --
select * 
	from retail_sales
where
	transactions_id is null
    or
	sale_date is null
    or
    sale_time is null
    or
    gender is null
    or
    age is null
    or
    category is null
    or
	quantity is null
    or
    cogs is null
    or
    total_sale is null;
    

-- DATA EXPLORATION --

-- What are total no. of sales ?
select count(*) total_sale 
	from retail_sales

-- How many unique customers we gained ?
select count(distinct customer_id) 
	from retail_sales

-- What are unique catergories ?
select distinct category 
	from retail_sales



-- DATA ANALYSIS ( Business key problem statements ) --

-- Q1. Write a SQL query to retrieve all columns for sales made on '2022-11-05:
-- Q2. Write a SQL query to retrieve all transactions where the category is 'Clothing' and the quantity sold is more than 4 in the month of Nov-2022:
-- Q3. Write a SQL query to calculate the total sales (total_sale) for each category.:
-- Q4. Write a SQL query to find the average age of customers who purchased items from the 'Beauty' category.:
-- Q5. Write a SQL query to find all transactions where the total_sale is greater than 1000.:
-- Q6. Write a SQL query to find the total number of transactions (transaction_id) made by each gender in each category.:
-- Q7. Write a SQL query to calculate the average sale for each month. Find out best selling month in each year:
-- Q8. Write a SQL query to find the top 5 customers based on the highest total sales:
-- Q9. Write a SQL query to find the number of unique customers who purchased items from each category.:
-- Q10. Write a SQL query to create each shift and number of orders (Example Morning <12, Afternoon Between 12 & 17, Evening >17):
-- Q11. Write a SQL query to calculate percentage of total revenue is generated by each gender?
-- Q12. Write a SQL query to find which day of the week generates the highest revenue?
-- Q13. Write a SQL query to find which age group generates the highest revenue?



-- Answers --
-- Q1. Write a SQL query to retrieve all columns for sales made on '2022-11-05:
select * from retail_sales
where 
	sale_date = '2022-11-05'

-- Q2. Write a SQL query to retrieve all transactions where the category is 'Clothing' and the quantity sold is more than 4 in the month of Nov-2022:
select * from retail_sales
where 
	category = 'Clothing' 
    and sale_date between '2022-11-01' and '2022-11-30' 
    and quantity >= 4;

-- Q3. Write a SQL query to calculate the total sales (total_sale) for each category.:
select category,
	sum(total_sale) as total_sales 
    from retail_sales 
group by category  

-- Q4. Write a SQL query to find the average age of customers who purchased items from the 'Beauty' category.:
select round(avg(age),2) as average_age_of_customers 
	from retail_sales 
    where category = 'Beauty'

-- Q5. Write a SQL query to find all transactions where the total_sale is greater than 1000.:
select * from retail_sales
	where total_sale > 1000 

-- Q6. Write a SQL query to find the total number of transactions (transaction_id) made by each gender in each category.:
select 
	category,
    gender,
    count(*) as total_transactions
from retail_sales
group by
		category,
        gender
order by category

-- Q7. Write a SQL query to calculate the average sale for each month. Find out best selling month in each year:
select 
	year,
    month,
    avg_sale
from
(
select
	YEAR(sale_date) as year,
    MONTH(sale_date) as month,
	avg(total_sale) as avg_sale,
    rank() over(partition by YEAR(sale_date) order by avg(total_sale) desc) as rnk
from retail_sales
group by
	year,
    month
) as t1
where rnk = 1

-- Q8. **Write a SQL query to find the top 5 customers based on the highest total sales :
select 
	customer_id,
    sum(total_sale) as total_sales
from retail_sales
group by customer_id
order by total_sales desc
limit 5

-- Q9. Write a SQL query to find the number of unique customers who purchased items from each category.:
select 
	category,
    count(distinct customer_id) as unique_customers
from retail_sales
group by category

-- Q10. Write a SQL query to create each shift and number of orders (Example Morning <12, Afternoon Between 12 & 17, Evening >17):
select
	case
		when HOUR(sale_time) < 12 then 'Morning'
		when HOUR(sale_time) between 12 and 17 then 'Afternoon'
		else 'Evening'
	end as shift,
    count(*) as total_orders
from retail_sales
group by shift

-- Q11. Write a SQL query to calculate percentage of total revenue is generated by each gender?
select
	gender,
    sum(total_sale) as total_revenue,
    round ( sum(total_sale) * 100 /
	(select sum(total_sale) from retail_sales),2 )
    as revenue_percentage
from retail_sales
group by gender;

-- Q12. Write a SQL query to find which day of the week generates the highest revenue?
select 
	DAYNAME(sale_date) as day_name,
    sum(total_sale) as total_revenue
from retail_sales
group by day_name
order by total_revenue desc

-- Q13. Write a SQL query to find which age group generates the highest revenue?
select 
	case
		when age < 25 then 'Under 25'
        when age between 25 and 40 then '25-40'
        when age between 41 and 60 then '41-60'
        else 'Above 60'
	end as age_group,
    sum(total_sale) as total_revenue
from retail_sales
group by age_group
order by total_revenue desc



-- END OF PROJECT, THANK YOU !